version: '3'
services:
  mysql:
    container_name: Tarea6SXE
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: prestashop
    networks:
      - prestashop_network
  prestashop:
    container_name: prestashop
    image: prestashop/prestashop:latest # Latest stable version of the PrestaShop, to see all availabl>
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      PS_INSTALL_AUTO: 1
      PS_DOMAIN:  localhost:8080
      DB_SERVER: myDefinitivesql
      DB_NAME: prestashop
      DB_USER: root
      DB_PASSWD: admin
    networks:
      - prestashop_network
networks:
    prestashop_network:






